### ISSUE TITLE
Why could autocannon produce more requests than wrk?

### ISSUE THREAD

**Issue by diorahman** [mcollina/autocannon#109]
Thanks for providing such a great tool for benchmarking.

What is the underlying explanation on the capability of autocannon to produce so many requests? Is that because of its internal `httpClient`? I could find that autocannon does not use the standard `http.request()` to initiate the request, why is that?

Thanks!

**Comment by mcollina** [comment]
Because it uses a different concurrency model, and it supports HTTP pipelining. We use a custom HTTP client that allows us to avoid any data allocation to send a new request.

**Comment by diorahman** [comment]
Thanks, @mcollina!

**Comment by Subomi** [comment]
@mcollina this is about event loops against threads?

**Comment by mcollina** [comment]
@Subomi yes, and autocannon supports HTTP/1.1 pipelining.

**Comment by Subomi** [comment]
Thanks ..
