### ISSUE TITLE
reqError callback throws nothing

### ISSUE THREAD

**Issue by binarytracer** [mcollina/autocannon#111]
```js

  function finishedBench() {
    console.log('finished benchmarking');
    // console.log(res);
    // console.log('finished bench', err, res);
  }

  const config = {
    url: 'http://localhost:3001/5968537fe66a6431eaa81ff8/5987c22fcea4da29f1f97b29',
    amount: 54000,
    timeout: 5400,
    connections: 3000,
  };
  const instance = autocannon(config, finishedBench);

  instance.on('reqError', (...args) => {
    console.log('---------------------');
    console.log(args);
    console.log('---------------------');
  });
```
Managed to trigger some errors.

but this is what i seen on terminal

```sh
...
[]
---------------------
---------------------
[]
---------------------
---------------------
[]
---------------------
---------------------
[]
...
```
it seems in trigger the **reqError** event, but it misses the "details" of the error.

but when i adjust the config to 
```js
  const config = {
    url: 'http://localhost:3001/5968537fe66a6431eaa81ff8/5987c22fcea4da29f1f97b29',
    amount: 54000,
    timeout: 5400,
    connections: 2000,
  };
```
there is no **reqError** event emitted. :+1: 

Questions

1. is the 3k concurrent connections quite suffocating to my app?
2. why the reqError event is throwing empty?
3. on connections,
` 
 -c/--connections NUM
        The number of concurrent connections to use. default: 10.
`, does this mean that the autocannon will try its very best to create the connections and fire them simultenously to my app?
4. im developing an app that will handle 8M requests  and generate 8M records at least per day, what will be the ideal configurations/settings i must use against it?

**Comment by mcollina** [comment]
Currently `'reqError'` does not emit an error, see: https://github.com/mcollina/autocannon/blob/34e23d6ffd46fcc457a28eda7d05952fd0b3b33b/lib/run.js#L210-L222.

It would be good to have it, would you like to send a PR?

As to your questions:

1. very likely, you might also be creating congestion to the TCP layer of your OS and hit the total number of file descriptors and/or other limits. Check the if the server is running at 100% of CPU.
2. see above
3. yes
4. a day timeframe is too wide. What will be your peak? 8M in 1 minutes (it's still less than a day :))?  Or 100 req/s?

**Comment by binarytracer** [comment]
> a day timeframe is too wide. What will be your peak? 8M in 1 minutes (it's still less than a day :))? Or 100 req/s?

i mean the **100 req/s**.

> 2. see above

i think this is exciting, first time though. Ill try.
