### ISSUE TITLE
Configuring for high concurrency

### ISSUE THREAD

**Issue by behrad** [mcollina/autocannon#113]
How we can simulate a real world load? Where concurrent users (=connections) are high, each make 3-4 requests, close. another user...

Does this really mean 10k users each issuing 2 requests?
`autocannon -c 10000 -p 1 -d 180 -t 15 --maxConnectionRequests 2`

**Comment by mcollina** [comment]
This tool is built to generate load on your application. By using HTTP pipelining and reusing the same sockets, you can generate more load than without. It is built to prove that  your application can hold a certain level of throughput.

If you want to very the TCP stacks, OSS network configuration, and verify a more real-world scenario, I recommend to use bees-with-machineguns, or other tools. They generate less load per host, but they reproduce a scenario closer to real-word by using multiple VMs on the cloud.
