### ISSUE TITLE
how to pass json?

### ISSUE THREAD

**Issue by mishelen** [mcollina/autocannon#124]
Hello
Im really broke my head trying to pass json to cannon. I want to send `application/json`
Let me show all cases that im try:
- `autocannon -m PUT -b "{\"playerId\":\"8797982347\" }" https://localhost:3434/player`
- `autocannon -m PUT -b '{"playerId":"8797982347" }' https://localhost:3434/player`
- ofcourse `autocannon -m PUT -b {"playerId":"8797982347" } https://localhost:3434/player`
- and many other cases like `--body=` or with `--input`. 

And also I try more from this with `-H "Content-Type: application/json"`

Can somebody help me and tell what type of escaping I must use for sending json

**Comment by mcollina** [comment]
which operating system are you using?

**Comment by mcollina** [comment]
what error are you getting?

**Comment by mishelen** [comment]
Hello) 
linux 16 & no any error

**Comment by mcollina** [comment]
`autocannon -m PUT -b '{"playerId":"8797982347" }' https://localhost:3434/player` work smoothly for me. So it might be something else. Can you add an http server that reproduce the problem as well?

**Comment by mishelen** [comment]
this is an ordinary express server with body-parser and construction like
`const {playerId} = req.body;` what could be easier?

**Comment by LandimTiago** [comment]
Hello, I have the same problem and I can't pass the request body through autocannon, did anyone find a solution?

I try it: 
npx autocannon -c 100 --renderStatusCodes -m POST -b '{usuario:USUARIO, senha:SENHA }' http://localhost:3001/api/v1/login

**Comment by james-innes** [comment]
Must admit I can't get this to work with express either using same variety of options.

**Comment by LandimTiago** [comment]
Hi, I found the solution, it is necessary to specify the header so that it accepts the body.

Exemple: 
URL=http://localhost:3000/api/v1/login

npx autocannon $URL -m POST \
    --header 'Content-Type: application/json' \
    --body '{"username": "USER_NAME","pass": "PASS_123"}' \
    --connections 100 \
    --duration 10 \
    --pipelining 1 \
    --renderStatusCodes
