### ISSUE TITLE
[QUESTION] About the request count

### ISSUE THREAD

**Issue by poppinlp** [mcollina/autocannon#132]
Hi. This is a real nice tool~ But i have a little question:

- The final output summary has request count such as `17k requests in 20s`. But what dose this means? Is it a count for requests who got response or just a count for sent requests?
- Dose autocannon send a batch of concurrent requests at regular intervals such as one batch per second? Seems not since the summary has a field named `Req/Sec`. But i have a test which has an avg latency 5000ms+ and 853 req/sec which means the statistic won't wait for the response. So could you please give me some informations about the send request logic.

Thanks :)

**Comment by mcollina** [comment]
> The final output summary has request count such as 17k requests in 20s. But what dose this means? Is it a count for requests who got response or just a count for sent requests?

These are requests that got a response.

> Dose autocannon send a batch of concurrent requests at regular intervals such as one batch per second? Seems not since the summary has a field named Req/Sec. But i have a test which has an avg latency 5000ms+ and 853 req/sec which means the statistic won't wait for the response. So could you please give me some informations about the send request logic.

autocannon fires another request after the previous one has finished. You can easily have 853 req/sec with a 5000ms latency as this is the number of completed requests per second. How many parallel connections are you using?

**Comment by poppinlp** [comment]
I set `-c 5000 -p 1 -d 20` to run that test.
I think i got what i want. The autocannon starts concurrent connections at a same time at the beginning. And then they are standalone, each one repeat itself after get response. I'm i right?

**Comment by mcollina** [comment]
Yes this is correct.
