### ISSUE TITLE
How I can see error messages

### ISSUE THREAD

**Issue by nairihar** [mcollina/autocannon#137]
Running 10s test @ http://localhost:3000
2000 connections

Stat         Avg      Stdev    Max     
Latency (ms) 70.3     180.7    3162.21 
Req/Sec      37394.86 11981.67 51351   
Bytes/Sec    7.45 MB  2.41 MB  10.2 MB 

262k requests in 11s, 51.8 MB read
2k errors (0 timeouts)

----------------------

Output shows I have 2k errors, I have checked nginx logs, I not see any errors.
How I can understand that point ?

**Comment by mcollina** [comment]
I don't think you can using the command line. You can using the JS API. Maybe would you like to send a PR to add switch to display them?

**Comment by nairihar** [comment]
ok thanks, If I will look source code than I will send PR

**Comment by mzavaletavargas** [comment]
Hello! Any update on this?

**Comment by kyegupov** [comment]
@mcollina you said "You can using the JS API." - can you perhaps divulge how exactly would one do that via the JS API?

**Comment by mcollina** [comment]
You need to listen to the `reqError` event in https://github.com/mcollina/autocannon#autocannon-events.

**Comment by mcollina** [comment]
Note that his is likely implemented in https://github.com/mcollina/autocannon/pull/217.

**Comment by LRagji** [comment]
```
const instance = autocannon();
instance.addListener("reqError", (err) => {
    console.log(err);
})
instance.addListener("error", (err) => {
    console.log(err);
})
```

Does this look right? @mcollina  cause its not printing anything even though i see 3 errors

**Comment by amroczeK** [comment]
> #217

It should be instance.on("reqError", console.error)

**Comment by LRagji** [comment]
@amroczeK isn't `addListner` and `on` aliases methods..?

https://stackoverflow.com/questions/54557718/what-is-the-difference-between-on-and-addlistener-in-node-js-events

**Comment by amroczeK** [comment]
> @amroczeK isn't `addListner` and `on` alias methods..?
> 
> https://stackoverflow.com/questions/54557718/what-is-the-difference-between-on-and-addlistener-in-node-js-events

I just tried instance.addListener("reqError"...) and it worked fine, but it's also been a long time since your original comment and now, so probably already fixed if there was an issue. Either usage works fine.
