### ISSUE TITLE
Misleading latency output

### ISSUE THREAD

**Issue by csabapalfi** [mcollina/autocannon#138]
This tool outputs latency averages and stddev which makes a lot of people assume Normal distribution that latencies usually don't have.

```
$ autocannon -c 1 -r 1 http://example.com
Running 10s test @ http://example.com
1 connections

Stat         Avg     Stdev  Max     
Latency (ms) 242.4   351.36 1296.58 
Req/Sec      1       0.45   2       
Bytes/Sec    1.57 kB 701 B  3.19 kB 

10 requests in 10s, 15.8 kB read
```

https://bravenewgeek.com/everything-you-know-about-latency-is-wrong
https://www.elastic.co/blog/averages-can-dangerous-use-percentile

**Comment by csabapalfi** [comment]
Can we use e.g. `p50` (median) `p99` and `max` instead or similar?

**Comment by thekemkid** [comment]
Check out the `-l` for this information via the command line. It's also accessible through the programmable interface.

**Comment by joaojeronimo** [comment]
@thekemkid  it's not about making percentiles more prominent on the defaults view, it's that averages and stdev don't make any sense for latencies.

**Comment by csabapalfi** [comment]
Would you guys accept a PR changing this behaviour to the proposed percentiles by default approach?

**Comment by mcollina** [comment]
Can you please make an example? Before/altre the change you are proposing.

Il giorno mer 20 giu 2018 alle 21:09 Csaba Palfi <notifications@github.com>
ha scritto:

**Comment by csabapalfi** [comment]
eg. it'd look something like this after the change

```
$ autocannon -c 1 -r 1 http://example.com
Running 10s test @ http://example.com
1 connections

Stat         p50     p99  Max     
Latency (ms) 242.4   1151.36 1296.58 
Req/Sec      1       1.45   2       
Bytes/Sec    1.57 kB 1701 B  3.19 kB 

10 requests in 10s, 15.8 kB read
```

**Comment by csabapalfi** [comment]
Or any other configuration you prefer. We could do `p50` (or just call that `median`) then `p95`, `p99`, `max`.

**Comment by mcollina** [comment]
The output is taken from `wrk`:

```
Running 30s test @ http://127.0.0.1:8080/index.html
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   635.91us    0.89ms  12.92ms   93.69%
    Req/Sec    56.20k     8.07k   62.00k    86.54%
  22464657 requests in 30.00s, 17.76GB read
Requests/sec: 748868.53
Transfer/sec:    606.33MB
```

I'm definitely +1 on including `p95` and `p99`.

I would still include avg, because it's relevant for req/sec and bytes/sec. So, I propose to have `avg`, `p50`, `p95`, `p99` and `max`.

Would that be ok for you?

**Comment by mcollina** [comment]
If you can send me a PR, I'll do a semver-major release asap.

**Comment by csabapalfi** [comment]
Cool, I'll try to get a PR in this week unless someone beats me to it :)

**Comment by csabapalfi** [comment]
I seem to be getting really busy for the next few weeks. Sorry about the delay.

Anyone who feels like can pick it up in the meantime.

**Comment by thekemkid** [comment]
Closing this as it has been fixed in new versions.
