### ISSUE TITLE
Add a way to make requests through a proxy

### ISSUE THREAD

**Issue by gajus** [mcollina/autocannon#150]
I was going to try to use autocannon to stress test a HTTP proxy. But there appears to be no way to configure [agent](https://nodejs.org/api/http.html#http_class_http_agent), which would allow use with https://www.npmjs.com/package/http-proxy-agent.

**Comment by mcollina** [comment]
Autocannon is not based on the agent model, nor it support HTTP proxies. I’ll be happy to review a PR if it does not affect throughput when disabled.

**Comment by gajus** [comment]
No worries. I ended up using wrk for the purpose.

https://github.com/wg/wrk/issues/162
