### ISSUE TITLE
Support a way to set headers and body before the client is started

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#16]
Maybe we can pass in a function that returns an object, or a function that accepts a client.

What do you think @thekemkid?

**Comment by thekemkid** [comment]
You can pass the headers and body you want your request to be built with as options to autocannon already, and they are passed to the clients. Do you want to add an extra method of passing the headers and body to the clients?

**Comment by mcollina** [comment]
The use case is "I want a custom header for each client".

**Comment by mcollina** [comment]
Released as 0.6.0.

**Comment by mcollina** [comment]
My bad, wrong issue.
