### ISSUE TITLE
Request multipart/form-data

### ISSUE THREAD

**Issue by mrbatista** [mcollina/autocannon#160]
Does the tool support requests with multipart/form-data?

**Comment by mcollina** [comment]
You would need to encode that manually, using something like https://www.npmjs.com/package/form-data. It would be fantastic to add the capability of doing this to autocannon itself.

**Comment by thekemkid** [comment]
@mrbatista Would this be something you would be interested in adding support for as a PR?

**Comment by hiepph** [comment]
Hi @mcollina can you show me an example of how to encode using `form-data`. For instance, I want to parse a body `multipart/form-data` with key `image` and value is a local image file.

**Comment by mcollina** [comment]
Unfortunately I don't have much time. The readme of form-data has a lot of examples: https://www.npmjs.com/package/form-data.

**Comment by dnlup** [comment]
Here's an example I have used, I hope it can be useful:
```
function bench({ url, file, connections, requests }) {
    return new Promise((resolve, reject) => {
        const buffer = readFileSync(file);
        const form = new FormData();
        form.append('file', buffer, {
            filename: basename(file),
            contentType: 'application/pdf',
        });
        const instance = autocannon(
            {
                title: `Convert from file upload with concurrency ${connections} | ${requests} Requests`,
                url: `${url.origin}/convert`,
                method: 'POST',
                headers: {
                    ...form.getHeaders(),
                },
                body: form.getBuffer(),
                connections: connections,
                amount: requests,
                timeout: 30,
            },
            (error, result) => {
                process.removeAllListeners('SIGINT');
                return error ? reject(error) : resolve(result);
            }
        );
        autocannon.track(instance, {
            renderLatencyTable: true,
        });
    });
}
```

**Comment by dnlup** [comment]
@mcollina @thekemkid What would be the best way to expose form-data submitting?

I was thinking exposing a separate option like:
```bash
autocannon --form '{ "encoding": "multipart/form-data", "body": { "image": { "type": "file", "path": "/path/to/file" }, "format": {"type": "text", "value": "jpegorelse"}}}'
```
that could be read also from file.

**Comment by mcollina** [comment]
That works

**Comment by tverilytt** [comment]
I wanted to run autocannon from the comnand-line with form file upload.
Ended up with something like this for GET / POST / DELETE of file.

'use strict'

const argv = require('minimist')(process.argv.slice(2));
const fs = require('fs');
const autocannon = require('autocannon');
const FormData = require('form-data');

let form;
if (argv.method === 'POST') {
  form = new FormData();
  form.append('file', fs.readFileSync(argv.file));
}

const headers = argv.headers.reduce((result, header) => {
  const key_value = header.split('=');
  result[key_value[0]] = key_value[1];
  return result;
}, {});

const options = Object.assign({},
  argv, {
  url: argv._[0],
  headers: Object.assign(headers, form && form.getHeaders()),
  ...form && { body: form.getBuffer() }
});

const result = autocannon(options);
autocannon.track(result);

**Comment by mcollina** [comment]
Support for form-data has been released as per v4.4.0. Check it out!

**Comment by kim0** [comment]
Thanks @mcollina for allowing form-data 👍 I'm facing a problem where the resulting form looks like
`Content-Disposition: form-data; name="foo"`
For it to be considered a real file upload, it is missing the `;filename=bar` attribute. How can I add that to the result ?

**Comment by dnlup** [comment]
Hi @kim0, it should have been injected here:

https://github.com/mcollina/autocannon/blob/7c55bd7d862e62d5090ebe7c9ad7502dfb8b8003/lib/run.js#L116

by `form-data`. Can you share the command you ran?

**Comment by mcollina** [comment]
I would recommend to open new issues for bug reports.

**Comment by kim0** [comment]
@dnlup I am trying to use it as a library, so the relevant line is
```
    form: '{ "field_2_fname": { "type": "file", "path": "app.js", "filename": "foo.js" } }',
```

I added this `filename` field, while trying to convince it to be sent as part of the reply. But it still doesn't show. If you can add an example in JS it would be great.

**Comment by dnlup** [comment]
@kim0 After some investigation I found that when the buffer is passed to `form-data` `.append` method, a `filepath/name` should be explicitly passed (because a Buffer is passed) in order to get the `filename` on the server:

*  https://github.com/mcollina/autocannon/blob/7c55bd7d862e62d5090ebe7c9ad7502dfb8b8003/lib/multipart.js#L33

See https://www.npmjs.com/package/form-data#void-append-string-field--mixed-value--mixed-options--

So as @mcollina suggested you should open a new issue because it is something that should be fixed. Given that I provided the PR for this I will try to work on it as soon as possible if there's no problem with that.
