### ISSUE TITLE
Does autocannon use the same connection for multiple requests?

### ISSUE THREAD

**Issue by honestserpent** [mcollina/autocannon#161]
I am trying to play around with Node.js sever.maxConnections parameter.

I've noticed that if I change the number of `maxConnections` while I am running autocannon, it doesn't look like it is affected. For instance, if I initially set `maxConnections=10` and run `autocannon -c 9 -d 10 localhost:3000`, the result is the following:

```
Running 10s test @ http://localhost:3000
9 connections

Stat    2.5% 50%  97.5% 99%  Avg     Stdev  Max     
Latency 0 ms 0 ms 1 ms  1 ms 0.11 ms 0.4 ms 17.6 ms 

Stat      1%      2.5%    50%     97.5% Avg     Stdev  Min     
Req/Sec   9831    9831    12127   12791 11945.6 875.9  9828    
Bytes/Sec 1.53 MB 1.53 MB 1.89 MB 2 MB  1.86 MB 137 kB 1.53 MB 

Req/Bytes counts sampled once per second.

119k requests in 10s, 18.6 MB read
```

If I run autocannon again, but I lower the maximum number of concurrent connections `server.maxConnections` to 1 while autocannon is running, the result is the same:
```
Running 10s test @ http://localhost:3000
9 connections

Stat    2.5% 50%  97.5% 99%  Avg     Stdev   Max      
Latency 0 ms 0 ms 1 ms  1 ms 0.12 ms 0.39 ms 25.91 ms 

Stat      1%      2.5%    50%     97.5% Avg      Stdev  Min     
Req/Sec   9679    9679    12431   12847 12094.19 909.16 9672    
Bytes/Sec 1.51 MB 1.51 MB 1.94 MB 2 MB  1.89 MB  142 kB 1.51 MB 

Req/Bytes counts sampled once per second.

133k requests in 11s, 20.8 MB read
```

Whereas, if I run autocannon after the I lowered the maximum number of concurrent connections `server.maxConnections` to 1, the result is significantly worse:
```
Running 10s test @ http://localhost:3000
9 connections

Stat    2.5% 50%  97.5% 99%  Avg     Stdev   Max       
Latency 0 ms 0 ms 1 ms  1 ms 0.05 ms 0.86 ms 147.66 ms 

Stat      1%     2.5%   50%    97.5%  Avg    Stdev   Min    
Req/Sec   1773   1773   3067   5331   3240.8 1009.71 1773   
Bytes/Sec 277 kB 277 kB 478 kB 831 kB 505 kB 157 kB  277 kB 

Req/Bytes counts sampled once per second.

32k requests in 10s, 5.06 MB read
3k errors (0 timeouts)
```

What could cause this? Maybe autocannon keeps the same connection open,and Node will not deny already opened connections, but only prevent **new** connections to be opened after the thresholdhas been reached?

**Comment by mcollina** [comment]
> What could cause this? Maybe autocannon keeps the same connection open,and Node will not deny already opened connections, but only prevent new connections to be opened after the thresholdhas been reached?

As you can [see](https://github.com/nodejs/node/blob/2b29df71ebc07cea87e14ed7f2d93e78f8b04b3c/lib/net.js#L1495-L1509), the check is enforced only on new connections.

**Comment by honestserpent** [comment]
Thank you, I didn't know where to look in Node.js code. Very clear
