### ISSUE TITLE
Bug, when http header has complex format

### ISSUE THREAD

**Issue by gleb-s** [mcollina/autocannon#170]
There is an issue, when my content-type is complex and looks like this: `content-type: application/json;odata=verbose`.

So, according to the logics from [this commit](https://github.com/phra/autocannon/commit/532349fb2318becacf73041604f6dea91394b36d#diff-b8cd744f56f8425866b8960637fe3f3bR96), I suppose, that my server is getting header like this:
`content-type: application/json;odata: verbose` - this syntax is incorrect.
So it would be nice, if someone could fix it.

_Originally posted by @gleb-s in https://github.com/mcollina/autocannon/issues/133#issuecomment-431030961_

**Comment by phra** [comment]
hi @gleb-s 

according to my commit only the first occurrence of `=` is matched using [indexOf](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) so I'm not sure about your supposition.

**Comment by phra** [comment]
hi @gleb-s 

i made https://github.com/mcollina/autocannon/pull/171 in order to fix your issue.
i have also added the required unit tests to prevent this from happening in the future.
thanks for reporting it.

/cc @mcollina
