### ISSUE TITLE
Add promise api

### ISSUE THREAD

**Issue by vjpr** [mcollina/autocannon#186]

**Comment by mcollina** [comment]
Would you like to help and send a PR?

**Comment by banyudu** [comment]
Should the promise API introduce breaking changes or just add new export member?

Is this ok? 

```javascript
module.exports.runAsync = require('util').promisify(run)
```

**Comment by mcollina** [comment]
I would prefer a case where `run` returns a promise if a callback is not specified.

**Comment by banyudu** [comment]
> I would prefer a case where `run` returns a promise if a callback is not specified.

Did you mean 

```javascript
function run (opts, cb) {
  const cbPassedIn = (typeof cb === 'function')

  cb = cb || noop

  // add 3 lines
  if (!cbPassedIn) {
    return require('util').promisify(run)(opts, noop)
  }
```
?

It's a break change, though

**Comment by mcollina** [comment]
No.

```js
function run (opts, cb) {
  const cbPassedIn = (typeof cb === 'function')

  cb = cb || noop

  // add 3 lines
  if (!cbPassedIn) {
    return new Promise((resolve, reject) => {
      run(opts, function (err, results) {
        if (err) return reject()
        resolve(results)
      })
    })
  }
```

**Comment by banyudu** [comment]
Thanks for your reply.

Besides `require('util').promisify` which requires node v8, there's another breaking change:
`run` returns an EventEmitter named `tracker`, so it's a breaking change if just return a promise instead.

Test cases like
```javascript
  tracker.on('done', (result) => {
    if (ondone) ondone()
    if (argv.json) {
      console.log(JSON.stringify(result))
    }
  })
```
will fail.

**Comment by mcollina** [comment]
I think the best way to solve this then is to make tracker a thenable. Essentially you can add the following method https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Syntax to Tracker. Then you'll be able to `await` it.

**Comment by banyudu** [comment]
Good idea, impressive!

**Comment by ryhinchey** [comment]
just reading through this issue and https://github.com/mcollina/autocannon/pull/205.  Can this issue be closed?
