### ISSUE TITLE
Rate Limiting is not Working

### ISSUE THREAD

**Issue by AndreyNikiforov** [mcollina/autocannon#187]
> $ autocannon --version
autocannon v3.2.0
node v10.13.0

> $ autocannon  --overallRate 5 http://localhost:8080
Running 10s test @ http://localhost:8080
10 connections

>┌─────────┬──────┬──────┬───────┬──────┬────────┬──────────┬────────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg    │ Stdev    │ Max        │
├─────────┼──────┼──────┼───────┼──────┼────────┼──────────┼────────────┤
│ Latency │ 0 ms │ 1 ms │ 4 ms  │ 5 ms │ 2.2 ms │ 26.18 ms │ 1009.48 ms │
└─────────┴──────┴──────┴───────┴──────┴────────┴──────────┴────────────┘
┌───────────┬───────┬───────┬────────┬────────┬─────────┬────────┬───────┐
│ Stat      │ 1%    │ 2.5%  │ 50%    │ 97.5%  │ Avg     │ Stdev  │ Min   │
├───────────┼───────┼───────┼────────┼────────┼─────────┼────────┼───────┤
│ Req/Sec   │ 212   │ 212   │ 2515   │ 3305   │ 2140.81 │ 1057.4 │ 212   │
├───────────┼───────┼───────┼────────┼────────┼─────────┼────────┼───────┤
│ Bytes/Sec │ 24 kB │ 24 kB │ 284 kB │ 374 kB │ 242 kB  │ 119 kB │ 24 kB │
└───────────┴───────┴───────┴────────┴────────┴─────────┴────────┴───────┘

>Req/Bytes counts sampled once per second.

>21k requests in 10.05s, 2.42 MB read

Expect to see in results:
5 Req/sec
50 total requests in 10 sec

**Comment by mcollina** [comment]
It’s likely the case. Would you like to fix it & send a pull request?

**Comment by thekemkid** [comment]
Fixed in #191 I believe
