### ISSUE TITLE
Documentation and validation work

### ISSUE THREAD

**Issue by thekemkid** [mcollina/autocannon#19]
Currently, the documentation doesn't show how to customise the headers on the request.

For the duration option, browsing the code, it is required, but never checked, @mcollina, should we put a check in for the duration and test it, or default it to some value, eg. `10`? Obviously, this will need a unit test and documentation work, too.

Supported HTTP methods should be documented.

Show the default value for the http pipelining value.

Update the `.track` doc, I left `outputStream` listed as a param name when I should have listed `opts`.

**Comment by mcollina** [comment]
Go ahead with doc and validations.

**Comment by mcollina** [comment]
IMHO connections and duration should always be specified, but Dave would like to have defaults
