### ISSUE TITLE
Problem running 2 autocannons in parallel when using setupClient()

### ISSUE THREAD

**Issue by frankorama** [mcollina/autocannon#194]
I have 2 files each running autocannon inside a promise.  Each file calls a different api end-point.

When I call the autocannon() method to create an instance I set the initial values of the header and body, and then change the values in an  `instance.on('response', handleResponse) method`.

Both files can run in parallel and everything works fine.

However, when I try to set the initial client header and body in the `setClient` method in file1, the body of file1 is suddenly being sent to the end-point of file2.

Can autocannon be run in parallel?  Are the instances distinct or is there shared code between the instances?

**Comment by mcollina** [comment]
This sounds like a bug. Would you like to send a PR?

**Comment by karpotkin** [comment]
Same issue. The more connections, the more net the module creates simultaneous requests at one time. For example, I want to create 4 connections. The first 3 connections will be sent by 1 request, and 4 connections will send 4 requests at once.

**Comment by mcollina** [comment]
@karpotkin would you like to send a PR?

**Comment by karpotkin** [comment]
@mcollina, ok, I will try

**Comment by mcollina** [comment]
Fixed in #206.
