### ISSUE TITLE
Typo in autocannon.track() description

### ISSUE THREAD

**Issue by msantagata** [mcollina/autocannon#197]
Hi,
just wanted to point out that there's a typo in the autocannon.track() documentation: the parameter should be `renderResultsTable` and not `renderResultTable` (note the additional "s").
Thanks!

**Comment by mcollina** [comment]
Would you mind opening a PR?

Il giorno ven 26 apr 2019 alle 14:29 msantagata <notifications@github.com>
ha scritto:

**Comment by msantagata** [comment]
Sure! I just did.

**Comment by thekemkid** [comment]
Closed via #198
