### ISSUE TITLE
Add support for a warmup interval before sampling

### ISSUE THREAD

**Issue by GlenTiki** [mcollina/autocannon#202]
This would mean that requests made in the first x amount of time during the warmup interval are not sampled. This should allow the server being tested to stabilise with the traffic from autocannon before sampling its load capabilities.

**Comment by afbarbaro** [comment]
I would upvote this request.  We're using [nextjs](https://nextjs.org/) and it does several things right as it boots (like compiling pages) that affect performance.  Having the ability to delay the sampling start will be key to get good measurements.
Thank you!

**Comment by simoneb** [comment]
How would you expect this to work? What pattern of requests should the warmup stage execute?

**Comment by mcollina** [comment]
Same as the other one.

**Comment by simoneb** [comment]
Doesn't it get tricky when the run parameters are (as they are by default) duration-based? Do you run the warmup for the same duration of the actual run? That would probably not be a sensible default unless the run is reasonably short. 

But if the run is, say, 60 seconds, how do you do the warmup run?

**Comment by mcollina** [comment]
You are right! Making this flexibble would need something like:

```
autocannon -c 100 -d 5 --warmup [ -c 1 -d 3 ] http://localhost:3000
```

You can use https://www.npmjs.com/package/subarg to get the subarg parameters
