### ISSUE TITLE
Add a bailout option

### ISSUE THREAD

**Issue by thekemkid** [mcollina/autocannon#21]
If running a test against a server which dies, maybe you want your test to stop?

In this case, it might be useful to allow a user to specify a threshold of errors within a specific timeframe to cause a bailout. This would surely damage perf though A better way of managing this is to just exit after the error threshold is hit (not needing an error timeframe).

Examples:

Say you have a server you are benchmarking for half an hour. The server dies after 10 minutes. To detect this, we could either:
Detect if there was 1000 errors from the server within the last second OR we could detect if there was 10000 errors overall.

**Comment by thekemkid** [comment]
Or maybe we could have a timeframe number, and just set an interval to clear the error count during that timeframe, and then the we just check against the number of errors, which is cleared per timeframe iteration. That might not damage perf like tracking the amount of errors since an error which is within the timeframe

**Comment by mcollina** [comment]
👍 send a PR.
