### ISSUE TITLE
Migrate CI to github actions

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#227]
As titled, then we can condense both AppVeyor and Travis in a single run

**Comment by davealbert** [comment]
![Screenshot 2020-03-10 at 08 54 01](https://user-images.githubusercontent.com/1281833/76295795-26eaae80-62ad-11ea-8245-dd790a5eef25.png)

I wanted to validate the environments are correct? 

All 4 Windows runs appear to die/fail at the same place:

`            
            Object.<anonymous> (node_modules/nyc/bin/wrap.js:27:4)
          test: should log error on connection error
          at:
            line: 5
            column: 1
            file: test/serial/run.test.js
            function: Object.<anonymous>
          source: "\r
          
            test('should log error on connection error', t => {\r
          
            ^
          
            \  t.plan(1)\r
          
            \  console.error = function (obj) {\n"
          ...
        
`

**Comment by mcollina** [comment]
We might need to fix the tests :/

**Comment by davealbert** [comment]
![Screenshot 2020-03-10 at 10 25 29](https://user-images.githubusercontent.com/1281833/76303344-7df68080-62b9-11ea-99dd-fc057c0ed5a9.png)


Changing `/test/serial/run.test.js` duration to 5, 4, and 3 have allowed tests to pass on Windows, setting it as 2 did fail every time. Setting as 3, and 4 failed some of the time.  Leaving it as 5 for now, I'm not sure if this will fail again in the future, but didn't want to crank it way up at this point.  Sending in PR. Leaving Travis and Appveyor active until we are sure we are satisfied with the GH Action.

**Comment by mcollina** [comment]
Perfect, thanks.
