### ISSUE TITLE
Autocannon sends two extra bytes at the end of the body, breaking the protocol

### ISSUE THREAD

**Issue by JerryCauser** [mcollina/autocannon#229]
I've tested [uWS](https://github.com/uNetworking/uWebSockets.js) HTTP server and passed little body in every http request. It produced strange results.
I asked (https://github.com/uNetworking/uWebSockets.js/issues/228) creator of uWS why it happens and he researched what _"autocannon sends two extra bytes at the end of the body, breaking the protocol.  uWebSockets does not close the connection immediately, as it has a different parsing strategy. "_

Can you fix it, please?

```
$ autocannon -c 100 -p 100 -d 10 -m POST -b '{"a":1}' http://0.0.0.0:8080
Running 10s test @ http://0.0.0.0:8080
100 connections with 100 pipelining factor

┌─────────┬──────┬──────┬───────┬───────┬──────────┬──────────┬────────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg      │ Stdev    │ Max        │
├─────────┼──────┼──────┼───────┼───────┼──────────┼──────────┼────────────┤
│ Latency │ 0 ms │ 0 ms │ 56 ms │ 82 ms │ 13.01 ms │ 34.33 ms │ 3618.88 ms │
└─────────┴──────┴──────┴───────┴───────┴──────────┴──────────┴────────────┘
┌───────────┬─────┬──────┬────────┬────────┬────────┬─────────┬─────────┐
│ Stat      │ 1%  │ 2.5% │ 50%    │ 97.5%  │ Avg    │ Stdev   │ Min     │
├───────────┼─────┼──────┼────────┼────────┼────────┼─────────┼─────────┤
│ Req/Sec   │ 0   │ 0    │ 1253   │ 3683   │ 1655.6 │ 1489.25 │ 26      │
├───────────┼─────┼──────┼────────┼────────┼────────┼─────────┼─────────┤
│ Bytes/Sec │ 0 B │ 0 B  │ 231 kB │ 678 kB │ 305 kB │ 274 kB  │ 4.78 kB │
└───────────┴─────┴──────┴────────┴────────┴────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.

17k requests in 10.15s, 3.05 MB read
7k errors (0 timeouts)
```

**Comment by mcollina** [comment]
I'll be happy to take a PR. I'm pretty convinced the current code is ok - but we'll see.

**Comment by alexhultman** [comment]
You can clearly see in Wireshark that autocannon sends invalid HTTP in the case of post. It sends Content-length: 7 followed by 7 bytes of content followed by 2 invalid bytes, breaking the protocol, causing the connection to eventually fail

It works just fine in wrk, https://github.com/wg/wrk as that client actually follows HTTP.

The protocol is like this:

header: value rn
header: value rn
rnrn
content

but autocannon sends

header: value rn
header: value rn
rnrn
content
rn <- those shouldn't be there, they break the protocol, botching the entire benchmark as things deteriorate to HTTP1.0 kind of connection close

**Comment by alexhultman** [comment]
![Screenshot from 2019-11-20 16-30-53](https://user-images.githubusercontent.com/3397140/69252442-47cead00-0bb3-11ea-8a88-14278c60a099.png)

**Comment by mcollina** [comment]
I’m happy to take a PR, I’m currently swamped.
Il 20 nov 2019, 16:32 +0100, Alex Hultman <notifications@github.com>, ha scritto:

**Comment by thekemkid** [comment]
Oh, it looks like you're correct. Thanks for investigating. We add those
/r/n for simpler logic for pipelining reasons, I think. I don't think we
realised it was invalid. I'll put together a fix.

Thanks again!
