### ISSUE TITLE
Timeouts for valid requests from a living server/connection

### ISSUE THREAD

**Issue by thekemkid** [mcollina/autocannon#23]
How are these handled and detected?

**Comment by mcollina** [comment]
Not at the moment. If a client dies, it is restarted. We should support a timeout! Any proposal on how to do thaf?

**Comment by thekemkid** [comment]
Maybe just use reTimer, and reset per reply? I'm not sure how perf will will be able to handle this thought :(

**Comment by mcollina** [comment]
let's do it and check.

**Comment by thekemkid** [comment]
Default timeout time on firefox is about 120 seconds [according to posts on StackOverflow](http://stackoverflow.com/questions/13582409/http-client-timeout-and-server-timeout), I am going to use this as the default time.

**Comment by mcollina** [comment]
a 120 s timeout is useless, given that we are trying to drive thousands of requests per second, one after the other.
