### ISSUE TITLE
SNI doesn't work without config

### ISSUE THREAD

**Issue by LinusU** [mcollina/autocannon#233]
Trying to benchmark against a service running behind API Gateway + Lambda on Amazon resulted in the connection not working (#232). Turns out that the SNI negotiation didn't work, and passing `--servername myhost.com` (not actual hostname) fixed it.

Since it wasn't my personal server I'm hesitant to give out the URL, but I think it should be easy to test against any server that requires SNI in order to negotiate HTTPS.

failing example:

```sh
autocannon -c 1 -a 1 https://foobar.myhost.com/
```

working example:

```sh
autocannon -c 1 -a 1 https://foobar.myhost.com/ --servername foobar.myhost.com
```

**Comment by silverwind** [comment]
Also ran into this when ranning against a SNI-only service. I think this module should by default send SNI servername based on the hostname in the URL to make this more intuitive and closer to actual client requests.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by silverwind** [comment]
Yes, I'll look into it.
