### ISSUE TITLE
[Question] What's alert handshake failure error with https websites?

### ISSUE THREAD

**Issue by tiendq** [mcollina/autocannon#234]
I think it's not `autocannon` issue but these websites' but I just don't know why. These websites are working well and google didn't help :(

`autocannon https://www.google.com.vn` works well, no error at all.

But when I tested below websites, both are NodeJS apps, I just got tons of same errors:

```bash
autocannon https://haypley.com
autocannon https://cryptobadge.app
```

Error:

```bash
at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }
{ Error: write EPROTO 4343698880:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 40
```

### envinfo
```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 4.21 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
```

**Comment by mcollina** [comment]
I think we are not passing the correct header for some website to work, you might add an header.

See https://github.com/openssl/openssl/issues/7147#issuecomment-419621673 for details

**Comment by tiendq** [comment]
Thanks for your link, I figured it out and below command worked well :)

`autocannon -s cryptobadge.app https://cryptobadge.app`

**Comment by LinusU** [comment]
See #233, this should probably happen automatically
