### ISSUE TITLE
http header values are trimmed instead of used verbatim

### ISSUE THREAD

**Issue by sam-github** [mcollina/autocannon#238]
It would be useful to be able to specify header values with exact whitespace, like `-H 'field= some value with ows    '`, but they appear to be [trimmed](https://github.com/mcollina/autocannon/blob/7c55bd7d862e62d5090ebe7c9ad7502dfb8b8003/autocannon.js#L145), I'm not sure why.

**Comment by mcollina** [comment]
I think I did it that way because devs are messy. I'm happy to change that if you'd like to send a PR.

**Comment by elirandav** [comment]
can I create a PR for this issue? @mcollina

**Comment by mcollina** [comment]
Go for it!
