### ISSUE TITLE
Allow specifying a filename when uploading a file through form

### ISSUE THREAD

**Issue by kim0** [mcollina/autocannon#240]
# Goal
What I'm trying to achieve is. I would like to benchmark an internal file uploading service. I want to use autocannon as a library from nodejs code. When specifying a file to upload using this format
`    form: '{ "field_2_fname": { "type": "file", "path": "myfile.pdf"" } }',`
I would like to be able to specify the "filename" content-disposition header.

Also, please make it so that the filename field, can be randomized using the familiar `[<id>]`, if that will not be the case by default.

More discussion at https://github.com/mcollina/autocannon/issues/160#issuecomment-578105069

Thanks @dnlup for offering to fix this bug 👍 

PS: I'm not much of a nodejs coder, so it would be awesome to attach a snippet (test?) that shows how to achieve this. Thanks!

**Comment by kim0** [comment]
Really appreciating the work @dnlup is adding to this project! I really hope to get this fix sometime this week. No pressure, and thanks for your work 👍

**Comment by dnlup** [comment]
Thanks @kim0 , my work has been adding bugs so far :laughing: . I will try to work on it this week.

**Comment by kim0** [comment]
Thanks a tons @dnlup .. really appreciating your help! Quick question, any idea if the filename field can be randomized using `[<id>]` syntax? Thanks!

**Comment by dnlup** [comment]
@kim0 Yes it can. You can try something like:

```js
autocannon({
  url: 'http://localhost:3000',
  connections: 10, //default
  pipelining: 1, // default
  duration: 10 // default,
  form: {
    fieldName: { type: 'file', path: '/some/path/file.ext', options: { filename: 'test_[<id>].ext' } }
 },
 idReplacement: true
}, console.log)
```
