### ISSUE TITLE
support custom TCP protocol

### ISSUE THREAD

**Issue by jerikchan** [mcollina/autocannon#245]
Can it support TCP protocol?such as 'grpc'、'thrift'、'protobuf' and so on.

**Comment by mcollina** [comment]
autocannon is a http/1.1 load tester.
Il 23 feb 2020, 18:40 +0100, Jerik Chan <notifications@github.com>, ha scritto:

**Comment by jerikchan** [comment]
Thanks for your Reply.

I am looking for a tool as good as autocanno to test the our RPC server by custom protocol.
