### ISSUE TITLE
navigator.userAgent is undefined

### ISSUE THREAD

**Issue by fanyuzzz** [mcollina/autocannon#257]
navigator is { userAgent: undefined }
userAgent should be a string.
I can not use navigator.userAgent.indexOf in website javascript
It causes TypeError: Cannot read property 'indexOf' of undefined

**Comment by mcollina** [comment]
Can you please include a full snippet on how to reproduce?

**Comment by fanyuzzz** [comment]
> Can you please include a full snippet on how to reproduce?

It's a SSR enviorment. It's my mistake, sorry.
