### ISSUE TITLE
Multipart file uploading does not work

### ISSUE THREAD

**Issue by orensolo** [mcollina/autocannon#264]
Hi, 
I am trying to use autocannon for testing file upload.
I invoke the following request :
$AUTOCANNON $URL/files -m POST -H "Content-Type:multipart/form-data"  -H "Authorization=$AUTHORIZATION_HEADER" -F '{ "fileName": { "type": "file", "path": "huge1G.txt"}}')

Where 
AUTOCANNON="taskset -c 3-5 /opt/autocannon-tests/node_modules/.bin/autocannon --amount 1 --connections 1 --bailout 5 --json"

The issue here is that the boundary is not added to the "Content-Type" header, the server expects the header to be something like "Content-Type:multipart/form-data;boundary=----------------------------f166e831278f"
But it gets in the header only "Content-Type:multipart/form-data".
So it seems that the server gets a request that is not in a multipart form format.

Is this a bug? Am I missing something here? 

Thanks in advance,
Oren

**Comment by mcollina** [comment]
Tbh, I never load tested multipart with autocannon. Check out https://github.com/mcollina/autocannon/pull/223/files and see if it can shed some light.

cc @dnlup

**Comment by dnlup** [comment]
@orensolo [here](https://github.com/mcollina/autocannon/blob/master/lib/run.js#L116) is where the request headers are added, and [here](https://github.com/mcollina/autocannon/blob/master/lib/multipart.js) is where the payload is constructed. There should be the boundary, so I think you are not missing anything. Give me some time to investigate further. What type of errors are you experiencing?

**Comment by dnlup** [comment]
I can confirm that the boundary is present in the requests.

```bash
$ ./autocannon.js -m POST -c 1 -a 1 -H "Authorization=test" -F '{ "test": { "type": "file", "path": "autocannon.js" } }' http://localhost:44781
```

![image](https://user-images.githubusercontent.com/15520377/86005849-73512a00-ba15-11ea-8774-d3bc775f68b1.png)

The server used in the above example is the same used in the tests. 

Can you share more information about the server environment you are working with?

How much is the size of the file that you're trying to send?

**Comment by orensolo** [comment]
Hi,

Thanks for the quick response.
I found what the problem was: I sent the request with -H "Content-Type:multipart/form-data"
But I should not add it when using autocannon. (It works if I don't add it)

**Comment by dnlup** [comment]
Yes, autocannon set that header for you.

Happy to see you resolved the issue.
