### ISSUE TITLE
Multipart uploading large file does not work

### ISSUE THREAD

**Issue by orensolo** [mcollina/autocannon#265]
Hi,

I am testing uploading large files using autocannon.
It works ok for small files. But when I try it with files that their size is larger than 100MB, the server fails with io.unExpectedEOF.
Note that if I use a simple curl to upload large files , then they are uploaded successfully.

Thanks,
Oren

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by orensolo** [comment]
Hi,
It seems that this is a bug in autocannon. So I will use other tools.
I will appreciate if you have the time to check and fix it if needed. As most testers will probably also need to test their application performance with large files

Thanks,
Oren

**Comment by admataz** [comment]
Hi @orensolo  - would you mind sharing the autocannon command you are using to try to do this, and if possible a version of the server accepting the multipart form? 

I have run some tests locally uploading large file (~348MB) to  a local minimal node fastify server, and found that limiting the number of connections reduced timeout errors. Running autocannon with default values (10 connections) caused a timeout. 

I think this may be down to the capabilities of your server and to replicate your success with curl you may need to limit the number of simultaneous connections autocannon opens

my command is below, it succeeds with 100 upload requests of the 348MB file, with 4 connections - no errors.  (takes a few minutes, locally)

```
autocannon -m POST http://localhost:3000/upload -F '{ "regularField": {"type": "text", "value": "this is a label"}, "filefield": { "type": "file", "path": "LNUG95.1.mp4", "options": { "filename": "myfilename" } } }' -a 100 -c 4
```
