### ISSUE TITLE
`idReplacement` not unique

### ISSUE THREAD

**Issue by jrasm91** [mcollina/autocannon#266]
Expected: `[<id>]` to be replaced with a unique id
Actual: `[<id>]` is not unique across requests

I ran the idReplacement sample with this modified handler, which parses the body and prints the email.
```nodejs
function handle(req, res) {
	let data = []
	req.on('data', chunk => {
		data.push(chunk)
	})
	req.on('end', () => {
		console.log(JSON.parse(data).email);
		res.end('hello world');
	})
}
```

I expected to see unique emails, but saw this instead (with `connections: 2, amount: 10`):
```
new-5DznV1MxQ8qpeLJIzpe+8A/0000000000@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000001@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000000@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000001@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000000@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000001@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000000@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000001@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000000@user.com
new-5DznV1MxQ8qpeLJIzpe+8A/0000000001@user.com
```
From what I can tell, the `this.rebuildRequest` is only called on the first request for each connection: https://github.com/mcollina/autocannon/blob/1fea4240163048719e6423bb73214eb653e1fe19/lib/requestIterator.js#L44-L49
Oppose the on each request:
https://github.com/mcollina/autocannon/blob/1fea4240163048719e6423bb73214eb653e1fe19/lib/requestIterator.js#L28-L31

I'm not sure if this is a problem with the example or a bug with the `idReplacement` feature.

The example, as is, doesn't produce unique email addresses. I did notice that adding: `setupRequest: req => req` to the request does generate a unique email address on each request. 
```
new-x//7JAdiRZGiy4cAd5KNvg/0000000000@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000001@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000002@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000003@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000004@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000005@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000006@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000007@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000008@user.com
new-x//7JAdiRZGiy4cAd5KNvg/0000000009@user.com
```

Is `setupRequest` required to use `idReplacement`?

**Comment by mcollina** [comment]
I think you might have spotted a bug. setupRequest should not be needed. Would you like to send a PR to fix?

**Comment by jrasm91** [comment]
Opened a PR for it. Really simple change. Not sure if the failing mac build is related to it or not. Thoughts?
