### ISSUE TITLE
Response body is not handled correctly

### ISSUE THREAD

**Issue by Jannis** [mcollina/autocannon#275]
I've found the following issue in the response handling:

## The issue

When the response data is sufficiently large (not sure what the threshold is), `onResponse` is called multiple times, each time with a partial body. This makes it really hard to e.g. validate the response body, like checking whether it is valid JSON and matches a certain structure.

The `expectedBody` feature is also broken because it's checked multiple times, again against partial body data, instead of the full response body.

## The reason

This is because `Client` checks `expectedBody` and calls `onResponse` every time `this.parser[HTTPParser.kOnBody]` fires. However, this can happen multiple times per response, and the handler will be passed a partial body every time.

## The fix

This can be fixed by

1. recording the full body in `resData[this.cer]` (e.g. via a new `body` field), and
2. only checking `expectedBody` and calling `onResponse` (via `this.requestIterator.recordBody()`) once in the `HTTPParser.kOnMessageComplete` handler.

**Comment by pola88** [comment]
Any news about this issue?

**Comment by mcollina** [comment]
the PR is waiting for some work to happen, maybe you can take over.

**Comment by Jannis** [comment]
Ah, yeah, I haven't had time to look into mocking responses that cause two `onResponse` calls yet.
