### ISSUE TITLE
Can someone explain to me the 4.78MB in the readme.md

### ISSUE THREAD

**Issue by Jdiego06** [mcollina/autocannon#278]
Hi, I don't know if this is the place to ask this, but ...

In the readme file, in the section where an example of the results returned by autocannon is shown, it is explained that in the worst case 4.78MB were downloaded, however I don't understand where this value comes from, according to the table shown.

I appreciate if someone can explain me. Thanks

**Comment by mcollina** [comment]
That is total number of bytes that have been downloaded through all the connections, including errors.

**Comment by Jdiego06** [comment]
@mcollina Sorry, but I don't really understand very well, how you deduce this 4.78MB from the table? What is the difference between this 4.78MB and the 2.29MB that appears in the 1% column?

**Comment by mcollina** [comment]
Autocannon sample the throughput once per second. In 1% of the samples, it reads 2.29MB.
