### ISSUE TITLE
setupRequest is being called before setupClient 

### ISSUE THREAD

**Issue by pola88** [mcollina/autocannon#279]
Hi,

I'm having an issue, In the setupClient I assign some variables on the context, to use different values between the connections, that I have to use in the first request, but `setupRequest` is being called before `setupClient`, Should not be called `setupClient` first?

Thank in advance,
Pola.

**Comment by mcollina** [comment]
I don't think the two are connected in any way. See https://github.com/mcollina/autocannon/blob/5112ca4375a49e6ae7f200a456951e73dd60b454/lib/httpClient.js#L34-L61 (`setupRequest` is called via `requestIterator`).

Can you please articulate what you are trying to do with a code example? Thanks

**Comment by pola88** [comment]
Yes, sure, this is what I'm trying to do:

```
let connection = 0;
export const setupClientEventHandlers = (client) => {
  client.requestIterator.context = {
    user: seed[connection], //the seed has the email and password
    connection,
  };

  console.log(`Init connection ${connection}`);
  connection++;
};

const loginRequest = ({
  method: 'POST',
  path: '/sessions',
  name: 'login',
  setupRequest: (req, context) => ({
    ...req,
    body: JSON.stringify({
      email: `${context.user.email}`,
      password: `${context.user.password}`
    }),
  }),
  onResponse: function (status, body, context) {
    ...
  }
});

autocannon({
  url: url,
  duration: 60,
  timeout: 5,
  setupClient: setupClientEventHandlers,
  headers: {
    ...
  },
  requests: [
    loginRequest,
    ...
  ]
});
```

And this throw an error about `can not read property user on undefined` and also the log `Init connection` is not shown before the error. That why I think that setup request is not calling before the first request

Thanks in advance

**Comment by mcollina** [comment]
I think you can just move https://github.com/mcollina/autocannon/blob/5112ca4375a49e6ae7f200a456951e73dd60b454/lib/httpClient.js#L34 after https://github.com/mcollina/autocannon/blob/5112ca4375a49e6ae7f200a456951e73dd60b454/lib/httpClient.js#L61.

Would you like to send a PR with a unit test?

**Comment by dnlup** [comment]
This change makes a lot of sense, but it might break the usage of `setBody` and `setHeadersAndBody` inside `setupClient`:

* https://github.com/mcollina/autocannon/blob/master/test/httpClient.test.js#L202
* https://github.com/mcollina/autocannon/blob/master/test/httpClient.test.js#L491

**Comment by salmanm** [comment]
@mcollina perhaps we should take `context` as one of the options (with default `{}`) and use that [here](https://github.com/mcollina/autocannon/blob/master/lib/requestIterator.js#L13)?

**Comment by mcollina** [comment]
> @mcollina perhaps we should take context as one of the options (with default {}) and use that here?

Yes, go for it.
