### ISSUE TITLE
Table of percentile vs req/s and latency explanation needed

### ISSUE THREAD

**Issue by dmngu9** [mcollina/autocannon#284]
when running autocannon, it generate the req/s and latency table with percentile. I have trouble interpreting these 2 tables. Can someone explain with example and clear details please?

**Comment by mcollina** [comment]
Every second, the number of  completed requests in that second is stored in a hdr histogram http://hdrhistogram.org/. That gives us those measures.

For the latency, we store the latency for every request in a hdr histogram.
