### ISSUE TITLE
Leverage worker threads

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#289]
We should use http://npm.im/piscina to to spawn a few threads 🧵.

cc @jasnell

**Comment by jasnell** [comment]
That depends entirely on what you're intending to do with them :).  Workers are ideal for cpu bound tasks, not I/O bound

**Comment by mcollina** [comment]
Autocannon is CPU-bound at high-throughput, despite what we can imagine. Connections are essentially independent from each other, we just need to forward the data for collection to the main process.

**Comment by jasnell** [comment]
Ok, the challenge there is that network connections are still bound by the libuv thread pool, which acts as a choke point. While every Worker thread has its own event loop, they all still share the same underlying thread pool.

**Comment by jasnell** [comment]
Scratch that... autocannon workload isn't leveraging the libuv threadpool that heavily. Piscina is going to be the wrong model, however. It is built around a work queue model that just doesn't fit for autocannon. You can still make use of workers but don't use piscina.

One additional utility you'll want to include: https://www.npmjs.com/package/nice-napi

**Comment by salmanm** [comment]
Done in #290 & #298
