### ISSUE TITLE
Is it possible to render the table with Result ?

### ISSUE THREAD

**Issue by fraxken** [mcollina/autocannon#296]
Hi,

I work in a project where we have automated the execution of several benchmarks and we keep all results in JSON format.

So I wondered afterwards if it was possible to render the Table by passing the JSON (JS) as argument? I would like to create a CLI to stdout the result of a benchmark at any time.

Thanks,
Best Regards,
Thomas

**Comment by mcollina** [comment]
That would be fantatic but it's not currently supported! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by fraxken** [comment]
Yes sure no problem, I will send a PR soon.

**Comment by slaphead** [comment]
Thanks @fraxken for adding this. It works very well!
