### ISSUE TITLE
Avg latency is wrong when using pipelining

### ISSUE THREAD

**Issue by simoneb** [mcollina/autocannon#315]
This was apparently addressed in a very old issue #15 but I am still seeing something wrong with latency when pipelining is used, especially in AVG. This is unless I'm interpreting the number wrong. I assume latency is the time a request takes to complete, as described in the docs.

Here's my web app:

```
const http = require("http");

http
  .createServer(function (req, res) {
    setTimeout(function () {
      res.end("hello world");
    }, 500);
  })
  .listen(3000);
```

And here's autocannon's output without and then with pipelining:

```
# without pipelining

autocannon http://localhost:3000
Running 10s test @ http://localhost:3000
10 connections

┌─────────┬────────┬────────┬────────┬────────┬───────────┬─────────┬────────┐
│ Stat    │ 2.5%   │ 50%    │ 97.5%  │ 99%    │ Avg       │ Stdev   │ Max    │
├─────────┼────────┼────────┼────────┼────────┼───────────┼─────────┼────────┤
│ Latency │ 499 ms │ 513 ms │ 522 ms │ 523 ms │ 510.27 ms │ 6.47 ms │ 523 ms │
└─────────┴────────┴────────┴────────┴────────┴───────────┴─────────┴────────┘
```

```
# with pipelining

autocannon http://localhost:3000 -p 2
Running 10s test @ http://localhost:3000
10 connections with 2 pipelining factor

┌─────────┬──────┬──────┬────────┬────────┬───────────┬───────────┬────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5%  │ 99%    │ Avg       │ Stdev     │ Max    │
├─────────┼──────┼──────┼────────┼────────┼───────────┼───────────┼────────┤
│ Latency │ 0 ms │ 0 ms │ 527 ms │ 528 ms │ 256.62 ms │ 256.65 ms │ 530 ms │
└─────────┴──────┴──────┴────────┴────────┴───────────┴───────────┴────────┘
```

As you can see, the AVG latency when using pipelining seems to be divided by the pipelining factor, which doesn't sound right to me, in the sense that the server is still responding in ~500ms, so the average latency should always be around that value. Possibly as a consequence of that, Stdev also becomes wrong.

**Comment by mcollina** [comment]
Good spot, PR? I _never_ look at the avg latency, just at 99% percentile.
