### ISSUE TITLE
Add title for requests

### ISSUE THREAD

**Issue by RafaelGSS** [mcollina/autocannon#319]
## Feature Request

Hey!

I'm creating an automated way to perform benchmarking of an API and I'm wondering whether would be great to have a title in each request performed.

For instance:

```js
autocannon(
  {
    headers: { 'Content-Type': 'application/json' },
    url: 'http://localhost:3000/',
    requests: [
      {
        method: 'POST',
        path: '/route',
        body: JSON.stringify({ example: '1' }),
      },
      {
        method: 'POST',
        path: '/route',
        body: JSON.stringify({ example: '2' }),
      },
    ],
  },
  console.log,
);
```

And it gives me a result like:

```sh
null {
  title: undefined,
  url: 'http://localhost:3000/',
  socketPath: undefined,
  connections: 10,
  pipelining: 1,
  workers: undefined,
  duration: 10.01,
  start: 2021-01-08T18:37:11.318Z,
  finish: 2021-01-08T18:37:21.327Z,
  errors: 0,
  timeouts: 0,
  mismatches: 0,
  non2xx: 1982,
  resets: 0,
  '1xx': 0,
  '2xx': 3969,
  '3xx': 0,
  '4xx': 1982,
  '5xx': 0,
  latency: {
    average: 16.33,
    mean: 16.33,
    stddev: 43.23,
    min: 1,
    max: 1255,
    totalCount: 5951,
    ...
  },
  requests: {
    average: 595.1,
    mean: 595.1,
    stddev: 202,
    min: 19,
    max: 716,
    total: 5951,
    ...
  },
  throughput: {
    average: 144595.4,
    mean: 144595.4,
    stddev: 49111.24,
    min: 4513,
    max: 173936,
    total: 1445963,
    p0_001: 4515,
    ...
  }
}
```

And would be great to analyze the requests separately. I mean, what's the average of path `/route` with payload 1? We can do it by creating two instances of `autocannon`, but I feel that it's not scalable with a lot of paths.

**Comment by mcollina** [comment]
This would indeed be useful. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by RafaelGSS** [comment]
@mcollina I took a look at it today and seems a major change since every metric should be placed in some namespace (title).

What is the problem to create an `autocannon` instance for every route titled? (Running all the instances at the same time). Perhaps some overhead in the server?

**Comment by mcollina** [comment]
> What is the problem to create an `autocannon` instance for every route titled? (Running all the instances at the same time). Perhaps some overhead in the server?


No problem, only the fact that the subsequent request cannot influence each other.
