### ISSUE TITLE
Provision to specify urlSafe when idReplacement is true

### ISSUE THREAD

**Issue by zebkailash** [mcollina/autocannon#320]
If we want to add an id after an email string eg: abc_randomStr@gmail.com but currently there is no way to create a url-safe id.

Currently, it creates a string **kailash-FZXY40aXS5C6Ph0KXs1KSQ/0000008544@gmail.com** which is an invalid email due to slash. Can this be supported in upcoming releases?

**Comment by mcollina** [comment]
> Can this be supported in upcoming releases?

It will if you send a PR!
