### ISSUE TITLE
how to figure out the results

### ISSUE THREAD

**Issue by Xiryl** [mcollina/autocannon#330]
Hi there,

What is the actual meaning of the field `results.errors` value?

For example, looking at the stats result printed at the console:

```sh
22k requests in 10.39s, 4.03 MB read
735 errors (0 timeouts)
```

And I wanted to understand the value of 735 errors to what it referred. So I looked at the json generated by autocannon containing the execution results, but I notice that actually all the requests generated received a `200 OK` response.

If `requests.sent` (23276) are the number of generated requests, and `2xx` (21541) are the received response, where 23276-21541=1735, I have lost `1735` response? and what is the meaning of `errors: 735` if I have 0 for timeout and there are no non 2xx errors? 

Is `735` the number of requests that due to errors did not start from auytocannon, and `1735` the number of requests that started but I received no response and autocannon lost tracking of it?

I have another question. Looking at the percentiles of requests, I see that the number of generated requests is actually not constant, but distributed more towards to the end, why? Hypothetically I thought that the number of requests was fairly constant and not distributed more towards the end. Is it normal?

I don't know if this is relevant, but I tested on a POST api, where I change the value of the body at each request (for test constraints where I need to generate sequential values) using the `instance.on('response', handleResponse);` method.

Thanks to those who will help me :)

```json
{
  "title": "session_1",
  "url": "http://localhost:3000",
  "connections": 1000,
  "pipelining": 1,
  "duration": 10.39,
  "start": "2021-01-30T13:31:58.925Z",
  "finish": "2021-01-30T13:32:09.312Z",
  "errors": 735,
  "timeouts": 0,
  "mismatches": 0,
  "non2xx": 0,
  "resets": 0,
  "1xx": 0,
  "2xx": 21541,
  "3xx": 0,
  "4xx": 0,
  "5xx": 0,
  "latency": {
    "average": 442.26,
    "mean": 442.26,
    "stddev": 203.58,
    "min": 141,
    "max": 2575,
    "p0_001": 141,
    "p0_01": 141,
    "p0_1": 144,
    "p1": 166,
    "p2_5": 320,
    "p10": 355,
    "p25": 381,
    "p50": 407,
    "p75": 439,
    "p90": 483,
    "p97_5": 1064,
    "p99": 1587,
    "p99_9": 2538,
    "p99_99": 2574,
    "p99_999": 2575,
    "totalCount": 21541
  },
  "requests": {
    "average": 2154.2,
    "mean": 2154.2,
    "stddev": 557.95,
    "min": 611,
    "max": 2628,
    "total": 21541,
    "p0_001": 611,
    "p0_01": 611,
    "p0_1": 611,
    "p1": 611,
    "p2_5": 611,
    "p10": 611,
    "p25": 2177,
    "p50": 2281,
    "p75": 2527,
    "p90": 2527,
    "p97_5": 2629,
    "p99": 2629,
    "p99_9": 2629,
    "p99_99": 2629,
    "p99_999": 2629,
    "sent": 23276
  },
 ...
}
```

**Comment by Xiryl** [comment]
Hi @mcollina can you help me with the meaning of this fields?
I need to check that the same number of generated requests have actually arrived on my database, but I don't have a match with the values that I find in this json.

What is the difference from `requests.sent` and `requests.total`? And whats the meaning of `errors` value?

**Comment by mcollina** [comment]
Errors -> 5xx status code
total -> number of requests completed with a response
sent -> number of requests sent

**Comment by Xiryl** [comment]
Hi @mcollina, I'm reopening this issue because 'm experiencing a problem again:
I created a server with fastify, where with `request.id` I print on stdout the sequence number of requests received, and with autocannon I generate the request, where get the following result:

```
"url": "http://localhost:3000",
  "connections": 100,
  "pipelining": 50,
  "workers": "1",
  "duration": 2.05,
  "start": "2021-03-06T10:52:39.644Z",
  "finish": "2021-03-06T10:52:41.694Z",
  "errors": 0,
  "timeouts": 0,
  "mismatches": 0,
  "non2xx": 0,
  "resets": 0,
  "1xx": 0,
  "2xx": 295,
  "3xx": 0,
  "4xx": 0,
  "5xx": 0,
  "requests": {
    "average": 147.5,
    "mean": 147.5,
    "stddev": 2.5,
    "min": 145,
    "max": 150,
    "total": 295,
    "p0_001": 145,
    "p0_01": 145,
    "p0_1": 145,
    "p1": 145,
    "p2_5": 145,
    "p10": 145,
    "p25": 145,
    "p50": 145,
    "p75": 150,
    "p90": 150,
    "p97_5": 150,
    "p99": 150,
    "p99_9": 150,
    "p99_99": 150,
    "p99_999": 150,
    "sent": 5200
  },
}
```

As you said `requests.total` is the requests completed with a response, and it match the `2xx`, and match the `request.id` that I receive on fastify (which has value of 295) and thats ok.

If autocannon generate 5200 `requests.sent` and I only get 295 requests on fastify, where did 4905 requests go? Because they're not even marked as an error. What meaning could I give to these requests that I have neither received a response to, nor ever arrived on the server?

thanks for the patience

**Comment by simoneb** [comment]
I guess the autocannon run terminated before sent - total requests were completed

**Comment by Xiryl** [comment]
Thank you very much @simoneb!
I used to set the `duration` value, and effectively, removing it solves the issue 
Thanks again!
