### ISSUE TITLE
Fix Intermittent CI

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#339]
As titled, CI often fails.

**Comment by nherment** [comment]
@mcollina can you please assign me to this or give me the right accesses to the repo to stabilize the CI?

**Comment by mcollina** [comment]
FYI, you don't need to be give permission to the repo. You should just do a fork: github actions will run there for you.

**Comment by mcollina** [comment]
is this done @nherment ?

**Comment by nherment** [comment]
Yes, I think it is. I could not reproduce the errors found earlier.

**Comment by nherment** [comment]
Fixed by #340, #341 and #343
