### ISSUE TITLE
onResponse method in the requests array is not triggered

### ISSUE THREAD

**Issue by karanjawa444** [mcollina/autocannon#351]
I am using one of the samples request-context.js but the onResponse method in the requests array is not triggered resulting in the value of the context object not getting populated to orchestrate the API calls. 
Would really appreciate the feedback and help!

**Comment by mcollina** [comment]
Could you paste an example to reproduce your problem?

**Comment by karanjawa444** [comment]
![image](https://user-images.githubusercontent.com/45726469/112647374-d2b25e00-8e1e-11eb-9898-baec86e43af0.png)

**Comment by karanjawa444** [comment]
And here is the sample file:

**Comment by mcollina** [comment]
I'm not sure what's the problem on your end, but things are working pretty well if you clone this repo and run `node ./samples/request-context`.

Even running `node request-context` using your code _works_. So you might be doing something wrong.

**Comment by karanjawa444** [comment]
Is autocannon support 8.17.0 version or need to upgrade node version?

**Comment by mcollina** [comment]
You might need to upgrade your Node.js

**Comment by karanjawa444** [comment]
Its working now with node 10. Thanks a lot for your help!
