### ISSUE TITLE
Unable to load PFX certificate with tlsOptions + workers

### ISSUE THREAD

**Issue by gpathak18** [mcollina/autocannon#391]
Example config -

`const instance = autocannon({
url: 'https://localhost:8080',
connection: 10,
workers: 3,
tlsOptions: {
pfx: fs.readFileSync('path/of/p12/keystore')
passphrase: 'test'
}
}`

When I use this config. I get 'Error: Unable to load PFX certificate'

This config works when I don't use 'workers' option.

**Comment by mcollina** [comment]
Good spot! There has to be some issues problem when sending the certificate over to the worker. 

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by radomird** [comment]
@mcollina & @gpathak18 I've created a PR, please review when you have time. Thanks.
