### ISSUE TITLE
Can't send JSON array as body

### ISSUE THREAD

**Issue by silverwind** [mcollina/autocannon#413]
```shell
$ autocannon -b '[]' https://localhost
body must be either a string or a buffer
```

Adding some logging, it seems this is an issue with the argument parser which decodes an object from the argument, `body` is `{"_":[]}` when it hits this verification function.

Ugly workaround:

```js
    } else if (body && Array.isArray(body._)) {
      bodyBuf = Buffer.from(`[${body._}]`);
```

**Comment by mcollina** [comment]
good spot! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by silverwind** [comment]
Possibly. I guess the [`subarg`](https://github.com/substack/subarg) is the culprit with its interpretion of `[` in arguments. It probably needs to be either replaced with `minimist` or above dirty workaround to be added.

**Comment by mcollina** [comment]
I'm kind of ok with the ugly workaround if it fixes your problem.
