### ISSUE TITLE
add a --name (or --title) swith

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#43]
The name (or title) switch should be emitted in the reaults. We may even add the time at which it finished. This makes the json results easier to debug.

**Comment by thekemkid** [comment]
Obviously this should be a top level instance param... what should it default to? I will add start and finish time to the json for debug purposes.

**Comment by mcollina** [comment]
`undefined`? so it stays empty if not specified

**Comment by thekemkid** [comment]
Okay, no problem.
