### ISSUE TITLE
customize the mismatch rules for expectBody?

### ISSUE THREAD

**Issue by GuanyuChen** [mcollina/autocannon#442]
hello, i want to get the mismatch result of pressure test。From the source code, I can see only one rule to compare expectBody  is "equal"。Is it possible to customize the validation function？like :

```
if (typeof this.opts.expectBodyValidate === 'function' &&  !this.opts.expectBodyValidate(resp.body) ) {
	return this.emit("mismatch", resp.body);
}
```

I can make a PR for this but I'd like to know if there are alternatives first.

**Comment by mcollina** [comment]
go for it!!!

**Comment by GuanyuChen** [comment]
hey bro. This PR is for the issue. 

#443 https://github.com/mcollina/autocannon/pull/443
