### ISSUE TITLE
 Semicolon insertion ❓ 

### ISSUE THREAD

**Issue by satanacchio** [mcollina/autocannon#451]
I've noticed that semicolons are not used at the end of statements. I know they are optional in most cases, but I was wondering what led to this choice and what are the pros/cons.

**Comment by GlenTiki** [comment]
This project uses the standard.js style for formatting code. Using a style/lint ruleset like this avoids wasting time agonizing about decisions that have little to no bearing on the performance of your application, it simply allows you to write code, autoformat it and work on the hard problems, not the superficial preference ones (like semis vs none). 

Read more there: https://standardjs.com/
