### ISSUE TITLE
JSON-body cannot be parsed in windows terminal

### ISSUE THREAD

**Issue by NilsDietrich** [mcollina/autocannon#458]
Hello guys, I have trouble to use autocannon 7.9.0 with a JSON-body specified via '-b' parameter in any windows console.
Here is my super basic express.js server:

```
const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const app = express()
const port = 3000

app.use(bodyParser.json())
app.use(cors())

app.post('/test', (req, res) => {
  console.log(req.body)
  res.json(req.body)
})

app.listen(port, () => console.log(`Example app listening on port ${port}`))
```

Now I try to use the following command:
`autocannon -c 1 -a 1 -m POST -H 'Content-Type: application/json' -b '{"a":2}' http://localhost:3000/test`

This causes the server to throw an error: "Unexpected token a in JSON at position 1" (autocannon receives non 200 response).
If I disable the body-parser by commenting line 7 the server logs "undefined".

The server should be set up correctly in windows. When I do 
```
await (await fetch('http://localhost:3000/test', {
  method: 'POST', headers: {'Accept': 'application/json','Content-Type': 'application/json'},
  body: '{"a":2}'
})).json()
```
in Chrome console, it correctly logs "{a:2}" on server and sends it back. 

This happens on Windows 11 cmd and powershell.
I tried the exact same on Ubuntu 22, there it works without any problem.

So do I have to escape something on windows cmd or is it a bug with autocannon?
Thanks for help!

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by bortolottidev** [comment]
I think its not an autocannon problem. It works fine with escape before double quotes:
`npx autocannon -c 1 -a 1 -m POST -H 'Content-Type: application/json' -b '{\"a\":2}' http://localhost:3000/test` 

(i added npx because i use to save autocannon in dev dep)

**Comment by NilsDietrich** [comment]
I tried escape the double quotes and adding npx, but for me it didn't help :/ 
Still gives an error or logs 'undefined' as body if I disable body-parser.
Are using windows 11 and node 16?

**Comment by NilsDietrich** [comment]
Okay I figured it out:
- If I use windows-powershell and escape quotes in body, like @bortolottidev said, it works.
- It seems to be impossible to use '-b' parameter on normal windows cmd.

Thanks for help!
Issue can be closed. Maybe add a notice in readme for '-b' parameter.
