### ISSUE TITLE
Recorded responses does not match total requests

### ISSUE THREAD

**Issue by viglucci** [mcollina/autocannon#462]
Hi!

First, great package. I have been using autocannon to test several projects and found it very useful. Thanks for your hard work!

## Env

```
autocannon v7.9.0
node v16.17.0
```

## Issue

I've noticed that the stats output after running a test returns numbers that don't always seem to match up. For example:

```
1612 2xx responses, 75 non 2xx responses
2k requests in 900.48s, 1.11 MB read
22 errors (22 timeouts)
```

The number of responses received doesn't seem to equal the number of requests executed.

`1612 + 75 + 22 = 1,709`

Does this imply that some responses were not received or are potentially still in flight when the test is completed?

Thanks

**Comment by mcollina** [comment]
Yes exactly
