### ISSUE TITLE
autocannon on port availability

### ISSUE THREAD

**Issue by brunolnetto** [mcollina/autocannon#477]
Hi fellows,

I woke up today with the following idea: commonly, there are tools to cover the main development roughness. The adverb "frictionless" is often use. Deployment is for me somehow enigmatic. In special, the setup of proper ports, load balance, assure operations security and sucess.

As there some way I can use autocannon to check available ports on a network e.g. EC2 instance, for me to setup?

Example: tools like PM2 or NGnix require some serial (hard) ordering on app ports setup.

**Comment by mcollina** [comment]
I don't understand the question. Could you clarify?

**Comment by brunolnetto** [comment]
Prior clarification: I am a junior developer. ;-P

Further clarification: NGnix and PM2 are used in the scale and require ports, oftentimes sequential, to scale some high-demand apps. The "basis-port" is set somewhere up i.e. an environment file `.env`, and the number of span ports.  There may (even must and, when not, should :-P) be solutions in the market to scale horizontally. 

The intended proposition is somewhat ad-hoc: use `autocannon` to shoot persistently the `2^16-1` available ports (in this case, a port subset due of protocol constraints), to verify information e.g. availability (famous log `this port is already in use`).  

Based on your original knowledge on `autocannon`, does it make a heck of sense?

**Comment by mcollina** [comment]
You don't need autocannon for this, any simple server using any language would do.

**Comment by brunolnetto** [comment]
Do you mind forwarding some `autocannon` use-case videos?

**Comment by mcollina** [comment]
I haven't recorded any in a while. 

Check out: https://youtu.be/G9Vkpe55Gu8
