### ISSUE TITLE
Plans to update `@types/autocannon`?

### ISSUE THREAD

**Issue by ElasticBottle** [mcollina/autocannon#495]
Current `autocannon` version is `7.12.0` but the types are still on `7.9.1`

Not sure if the discrepancy is intended, but notably, the verification functions are missing from types.

![image](https://github.com/mcollina/autocannon/assets/44563205/418d6986-8ad4-4a5c-824f-b9aad3928a79)

**Comment by mcollina** [comment]
`@types/autocannon` are not maintained by me.
