### ISSUE TITLE
Traefik ignores autocannon when setting Host header

### ISSUE THREAD

**Issue by cberescu** [mcollina/autocannon#502]
When using autocannon with Host header  it is ignored by traefik proxy. The issues seems that the Host is added 2 times to the requests. 

`autocannon -c 1 -d 5 -H 'Host: example.com'  http://127.0.0.1/`

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
