### ISSUE TITLE
Icon without text

### ISSUE THREAD

**Issue by Zeko369** [mcollina/autocannon#503]
Hey,

I'm working on a **[fig](https://fig.io/)** spec for Autocannon and would like to use an icon for autocomplete (example bellow), the issue is that the current official logo isn't square and can't be used

![CleanShot 2023-12-15 at 15 43 38](https://github.com/mcollina/autocannon/assets/3064377/6abf3adf-c356-44a1-b595-133095c51be5)

I'd love to create a PR with a smaller logo (just the left part of the current one) and use that for fig, but wanted to ask @mcollina here first if that's ok

**Comment by mcollina** [comment]
Sure thing, go ahead
