### ISSUE TITLE
Is there a way to generate a url for each request?

### ISSUE THREAD

**Issue by kkogovsek** [mcollina/autocannon#512]
I'd like to benchmark `POST` requests where I could pass a random id at the end of path.
I tried using `setupClient` to change the url, but I'll only change the first request of each client.

**Comment by mcollina** [comment]
I don't think this is possible but it would be a great feature addition

**Comment by kkogovsek** [comment]
Any pointers on how an api for that could look like (I'm happy to do a PR, write tests...)?
In cli setting alone it could work similarly to idInjection in body (with `[id]`), while it'd be awesome to have the config object accept url as a function

**Comment by mcollina** [comment]
You'll need to modify https://github.com/mcollina/autocannon/blob/master/lib/httpRequestBuilder.js
