### ISSUE TITLE
TypeError: colorize is not a function

### ISSUE THREAD

**Issue by ibrahidm** [mcollina/autocannon#529]
When I run this command: 

```
autocannon -c 100 -t 1 --renderStatusCodes http://localhost:3000
```

I get the following error: 

```
/<path>/node_modules/.pnpm/autocannon@7.15.0/node_modules/autocannon/lib/printResult.js:46
        statusCodeStats.push([colorize(statusCode), stats.count])

TypeError: colorize is not a function
    at /<path>/node_modules/.pnpm/autocannon@7.15.0/node_modules/autocannon/lib/printResult.js:46:31
    at Array.forEach (<anonymous>)
    at printResult (/<path>/node_modules/.pnpm/autocannon@7.15.0/node_modules/autocannon/lib/printResult.js:43:43)
    at EventEmitter.<anonymous> (/<path>/node_modules/.pnpm/autocannon@7.15.0/node_modules/autocannon/lib/progressTracker.js:79:28)
    at EventEmitter.emit (node:events:531:35)
    at _cb (/<path>/node_modules/.pnpm/autocannon@7.15.0/node_modules/autocannon/lib/init.js:76:13)
    at Timeout.tickInterval (/<path>/node_modules/.pnpm/autocannon@7.15.0/node_modules/autocannon/lib/run.js:150:9)
    at listOnTimeout (node:internal/timers:583:11)
    at process.processTimers (node:internal/timers:519:7)
```

I am testing against a Nuxt application, and I do not get the same error when I do not include the `--renderStatusCode` flag. 

I also do not get the same error if I reduce the number of connections.

**Comment by mcollina** [comment]
I guess it's a pnpm resolution issue? Have you tried with a `npx autocannon` from a different folder?

**Comment by ibrahidm** [comment]
I did, but same result! 

I also currently I have a fresh Nuxt application open side-by-side with mine and trying to test scenarios against the two. 

What is interesting is I get the above error if my application throws the following as one of the responses: 

```
[10:42:05 AM]  ERROR  [h3] [unhandled] connect ECONNREFUSED /var/folders/tt/4s_yvqq11tnbvx7q3yy9q7gm0000gn/T/nitro/worker-41364-1.sock

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) (repeated 239 times)
  ```

When I eliminate the component that produces the above response, autocannon returns the following response:

```

┌─────────┬────────┬─────────┬─────────┬─────────┬───────────┬────────────┬─────────┐
│ Stat    │ 2.5%   │ 50%     │ 97.5%   │ 99%     │ Avg       │ Stdev      │ Max     │
├─────────┼────────┼─────────┼─────────┼─────────┼───────────┼────────────┼─────────┤
│ Latency │ 337 ms │ 2543 ms │ 4590 ms │ 4609 ms │ 2540.8 ms │ 1243.68 ms │ 4622 ms │
└─────────┴────────┴─────────┴─────────┴─────────┴───────────┴────────────┴─────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev  │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼────────┼─────────┤
│ Req/Sec   │ 194     │ 194     │ 337     │ 356     │ 315.11  │ 48.97  │ 194     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼────────┼─────────┤
│ Bytes/Sec │ 1.04 MB │ 1.04 MB │ 1.81 MB │ 1.91 MB │ 1.69 MB │ 262 kB │ 1.04 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┴─────────┘
┌──────┬───────┐
│ Code │ Count │
├──────┼───────┤
│ 200  │ 3151  │
└──────┴───────┘


Req/Bytes counts sampled once per second.
# of samples: 10

6k requests in 10.05s, 16.9 MB read
723 errors (0 timeouts)
```

Thanks for taking the time to respond! I do think it's very possible the problem is on my end, but the behaviour is strange so I thought to open the ticket. I'll keep digging!

**Comment by ibrahidm** [comment]
I'm still curious, but the problem goes away when I run `autocannon` against the built application. I'm going to close the issue as I think it's something going on locally, especially considering nobody else has run into the same problem. 

Thank you again, and sorry to trouble you!

**Comment by paul-uz** [comment]
I'm seeing this issue too, with autocannon installed globally.

**Comment by karankraina** [comment]
@mcollina I just faced this too. I debugged a little and found `result.statusCodeStats` has an entry with `undefined` key.
```js
statusCodeStats : {
"200": { /*  data */},
"404": { /*  data */},
"undefined": { /*  data */},
}
```

This is breaking the following line
https://github.com/mcollina/autocannon/blob/225e3a30a6adb8111cd8cf60759bd601936764be/lib/printResult.js#L176

I can open a PR to handle this in `printResult` as a fallback color but am not sure why status code aggregator has `undefined`

**Comment by karankraina** [comment]
@mcollina Your comments here please ?
