### ISSUE TITLE
colors disabled when -j is set and we are writing to a file

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#59]
As titled, we might probably want to override some stuff in [`chalk`](https://github.com/chalk/chalk).

Chalk is disabled because of a check in https://github.com/chalk/supports-color/blob/master/index.js.

See https://github.com/chalk/supports-color/blob/master/index.js#L41-L43.

We can either internalize that check, or sending them a PR to expose that as a function that accepts a stream. Or maybe it's just a new module.

**Comment by thekemkid** [comment]
I think that a pr is the best approach. Will do later 👍

**Comment by mcollina** [comment]
See also https://github.com/isaacs/color-support.
