### ISSUE TITLE
precompile native-hdr-histogram binaries for different versions

### ISSUE THREAD

**Issue by davidmarkclements** [mcollina/autocannon#6]
A fairly common use case involves changing node versions and then profiling, it would be cool if you didn't have to reinstall

**Comment by mcollina** [comment]
That would be truly awesome.
In your experience, it is an hard thing to maintain? The problem is doing 3 OSes, Mac, Windows and Linux, and multiple versions of Node (4 and 6 at least).
Have you got any experience?

cc @marcopiraccini and @mcdonnelldean.

**Comment by davidmarkclements** [comment]
I don't but it would be an interesting adventure, cylon.js managed it, using http://npm.im/node-pre-gyp, and even automated it with travis, and appveyor

**Comment by mcollina** [comment]
I'm not a fan of prebuilts, as they create a massive maintenance overhead.
Let's do it if this reaches high usage.

Il giorno sab 7 mag 2016 alle 18:46 David Mark Clements <
notifications@github.com> ha scritto:

**Comment by mcollina** [comment]
@thekemkid it's just a matter of bumping the dependency of native-hdr-histogram!

**Comment by thekemkid** [comment]
I'm waiting until we have a successful build published to s3, because otherwise the dependency download in travis will fail 👍

**Comment by davidmarkclements** [comment]
so we're doing this then? *awesome*

**Comment by mcollina** [comment]
No, it's _done_. Just waiting for the prebuilts to finish before releasing.
