### ISSUE TITLE
disconnect and reconnect clients after a while

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#65]
We should be able to force a dns lookup each X requests to support AWS ELBs:

> Single Client Tests
In single client tests, a load generator will issue requests to the server using the same client. In most cases, the client does not re-resolve the DNS after the test is initiated. A good example of this type of test is Apache Bench (ab). If you are using this type of testing tool, there are two options:
> 
> * Write discrete tests at a given sample size and concurrency then start a new set of tests and invoke these tests separately so that the client will re-resolve the DNS (possibly even forcing a re-resolution depending on the operating system and other factors). It is important to save detailed request logs so you can aggregate the logs for a single view of the request details.
> * Launch multiple client instances and initiate the tests on the different instances at approximately the same time. AWS CloudFormation can help you do this by creating your load test script and launching multiple clients, then simply issuing remote SSH commands to initiate the tests. You may want to bring up more load generating clients based on Auto Scaling rules (for example, when the average CPU of other load clients reaches a certain level, add more load generators).
>
> However, depending on the load you are trying to generate, your test may be constrained by the client's ability to issue requests. In this case, you need to consider distributed tests.

**Comment by mcollina** [comment]
@thekemkid this is not urgent, we'll leave this open.

**Comment by thekemkid** [comment]
Should this reconnect metric be timer based or request count based?
