### ISSUE TITLE
manually resolve dns entries and rotate them between the connections

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#66]
Similar to #65.

I'm not 100% sure that it's needed.

**Comment by thekemkid** [comment]
Are you working on this and/or #65? I can crack into them tomorrow if its not high priority

**Comment by mcollina** [comment]
I need to do some research on this one first. The other is up to take.
Il giorno mer 13 lug 2016 alle 19:44 Glen Keane <notifications@github.com>
ha scritto:

**Comment by mcollina** [comment]
This is not needed and automatically implemented.
