### ISSUE TITLE
Should --json default to true when stdout is not a tty?

### ISSUE THREAD

**Issue by thekemkid** [mcollina/autocannon#67]

**Comment by mcollina** [comment]
I would leave things as they are for now.

**Comment by mcollina** [comment]
I'm interested in what @bzoz think about this.

**Comment by bzoz** [comment]
I think not. In things like Visual Studio Code it would make autocannon output json by default to "console window", it would be confusing for new users.

**Comment by mcollina** [comment]
All good then, are you happy with the current output?

**Comment by bzoz** [comment]
Yeah, it is good.
