### ISSUE TITLE
Support some form of threading/multi process benchmarking.

### ISSUE THREAD

**Issue by thekemkid** [mcollina/autocannon#78]
Maybe we should use node's cluster, or node-webworker-threads. Or is a single event loop enough to drive this?

**Comment by mcollina** [comment]
some bits: a single event loop is _usually_ enough to saturate a single (virtual) network card using the basic API (what's exposed via the cli tool). If the data is customized a lot, it might not be enough.

I would rather focus on supporting a networked mode, where we can coordinate multiple autocannon instances across different virtual machines, to leverage more bandwidth. The key difficulty is probably in hdr histogram, as a) I do not know if two histograms can be combined into one and b) we do not want to store a transmit all the samples to centralize the generation of the histogram.

The same principle than could be used locally.
