### ISSUE TITLE
Export the progress bar and reporting

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#9]
The goal is to let users build their own tool if they want to, embedding autocannon.

**Comment by thekemkid** [comment]
How do you want the progress bar exported? I am thinking allowing the user to enter `renderProgressBar: true` in the options parameter will render the progress bar, as the bar itself is not an object which you can log, the output to console is managed internally in the progress bar.

To customise the rendering output of the bar, I would like to allow users to enter a `progressBarDisplay: SOME_STRING` in the options parameter, which would take a string in the format of the [progress-bar](https://github.com/visionmedia/node-progress) module.

Does that sound okay for the progress bar?

Reporting: Do you just mean logging the run results in the table format?
