### ISSUE TITLE
should install over HTTP proxies

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#91]
as titled

**Comment by thekemkid** [comment]
Whats happening? I'm not sure I understand this issue.

**Comment by mcollina** [comment]
I think node-pre-gyp is not passing through proxy servers on windows.

**Comment by thekemkid** [comment]
node-pre-gyp should fall back to node-gyp in the case AWS is inaccessible. I'll try dig into this

**Comment by mcollina** [comment]
@thekemkid and then it fails because it's missing python and the compiler.

**Comment by mcollina** [comment]
(with a bad error)

**Comment by robcalcroft** [comment]
Im also experiencing this

**Comment by mcollina** [comment]
This was fixed in version 0.17  🎉
