### ISSUE TITLE
Difference between average and mean in json output

### ISSUE THREAD

**Issue by Shadowbeetle** [mcollina/autocannon#97]
I saw both average and mean in the json output, a they used as aliases or mean is different from the arithmetic mean here?

**Comment by thekemkid** [comment]
I think average to be the _median_ here, not the mean. Need to double check, though, and will confirm

**Comment by thekemkid** [comment]
Wait, I'm wrong, the average is also the mean, its added for compatibility with wrk. see code here: https://github.com/thekemkid/hdr-histogram-percentiles-obj/blob/master/index.js

**Comment by thekemkid** [comment]
Closed because this answers your question, feel free to reopen if you have more 👍

**Comment by Shadowbeetle** [comment]
I'm good, thanks a lot!
