### ISSUE TITLE
test koa@next throw Error: write EPIPE

### ISSUE THREAD

**Issue by i5ting** [mcollina/autocannon#99]
test koa@next

```
'use string'

var Koa = require('koa')
var app = new Koa()

app.use(function (ctx, next) {
    ctx.body = { hello: 'world' }
})

app.listen(3000)
```

throw Error: write EPIPE

```
  Error: write EPIPE
      at exports._errnoException (util.js:1022:11)
      at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
```

is this autocannon's issue?

**Comment by davidmarkclements** [comment]
which process gives EPIPE? Koa process or autocannon? Try setting ctx.body to a string instead of obj

**Comment by i5ting** [comment]
@davidmarkclements hi, autocannon process

in koa 2.x it will be convert json default, see here  https://github.com/koajs/koa/blob/v2.x/lib/response.js#L177

**Comment by mcollina** [comment]
I can't reproduce. Can you please provide detailed instructions?

**Comment by i5ting** [comment]
@mcollina there's no more details。you can run koa@2 demo,and then do autocannon

**Comment by i5ting** [comment]
https://github.com/sletjs/benchmark  

```
$ npm i
$ node bin.js
```

**Comment by i5ting** [comment]
it will happen at most time

**Comment by mcollina** [comment]
I do not think that happens from `autocannon` codebase, but it is in `koa`.

Could you run the two thing separately?

**Comment by Asher-Tan** [comment]
same problem
``` js
const Koa = require('koa');
const app = new Koa();

app.use(async ctx => {
	ctx.body = 'hello world!';
});

app.listen(4000);
```
``` shell
autocannon -c 100  -d 5 -p 10 -l http://localhost:4000
```

``` shell
Error: write EPIPE
      at _errnoException (util.js:1041:11)
      at WriteWrap.afterWrite [as oncomplete] (net.js:858:14)
```

**Comment by hueniverse** [comment]
This is definitely a Koa issue. I am running them on two separate boxes. Koa keep spitting out this error.

**Comment by mcollina** [comment]
Closing then, thanks for confirming!

**Comment by hueniverse** [comment]
BTW, I think this issue explain why I am getting inconsistent numbers for Koa. It is the only framework of the set I am testing that is producing unstable results.

**Comment by xsbchen** [comment]
same problem，use wrk is fine

**Comment by txchen** [comment]
I got same problem, autocannon -> fastify
